### ISSUE TITLE
CollectionJSON call to_json error

### ISSUE THREAD

**Issue by hotarubi** [apotonick/roar#102]
define representer:
```ruby
    module JobRepresenter
      include Roar::Representer::JSON::CollectionJSON

      items(class: Job) do

        property :category
      end
    end
```

then call 
```ruby
[Job.first].extend(JobRepresenter).to_json
```

get error:
```ruby
NoMethodError: undefined method `to_hash' for #<OpenStruct>
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/serializer.rb:24:in `block in serialize'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/binding.rb:122:in `evaluate_option'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/serializer.rb:23:in `serialize'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/serializer.rb:16:in `call'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/binding.rb:141:in `serialize'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/bindings/hash_bindings.rb:22:in `write'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/binding.rb:57:in `write_fragment_for'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/binding.rb:52:in `write_fragment'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/binding.rb:35:in `block in compile_fragment'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/binding.rb:122:in `evaluate_option'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/binding.rb:33:in `compile_fragment'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/mapper.rb:64:in `compile_fragment'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/mapper.rb:30:in `serialize_property'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/mapper.rb:22:in `block in serialize'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/mapper.rb:21:in `each'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/mapper.rb:21:in `serialize'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable.rb:39:in `create_representation_with'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/hash.rb:35:in `to_hash'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/representable-2.0.3/lib/representable/json.rb:34:in `to_json'
  from (irb):13
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/railties-4.1.4/lib/rails/commands/console.rb:90:in `start'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/railties-4.1.4/lib/rails/commands/console.rb:9:in `start'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:69:in `console'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  from /Users/user_name/.rvm/gems/ruby-1.9.3-p547/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
  from bin/rails:4:in `require'
```

Sorry not pretty sure I should raise this to roar or representable.

**Comment by apotonick** [comment]
I removed CollectionJSON as I don't have any feedback on usage. Sorry. :heart:
