### ISSUE TITLE
representable/coercion.rb:21:in `block in included': undefined method `register_feature'

### ISSUE THREAD

**Issue by joevandyk** [apotonick/roar#120]
Am I doing something really stupid here?

```
$ cat g.rb
require 'roar'
require 'roar/coercion'

module SongRep
  include Roar::Coercion
end

$ bundle exec ruby g.rb
/usr/local/tanga/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/representable-2.1.3/lib/representable/coercion.rb:21:in `block in included': undefined method `register_feature' for SongRep:Module (NoMethodError)
	from /usr/local/tanga/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/representable-2.1.3/lib/representable/coercion.rb:19:in `class_eval'
	from /usr/local/tanga/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/representable-2.1.3/lib/representable/coercion.rb:19:in `included'
	from /usr/local/tanga/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/roar-1.0.0/lib/roar/coercion.rb:16:in `include'
	from /usr/local/tanga/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/roar-1.0.0/lib/roar/coercion.rb:16:in `block in included'
	from /usr/local/tanga/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/roar-1.0.0/lib/roar/coercion.rb:15:in `class_eval'
	from /usr/local/tanga/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/roar-1.0.0/lib/roar/coercion.rb:15:in `included'
	from g.rb:5:in `include'
	from g.rb:5:in `<module:SongRep>'
	from g.rb:4:in `<main>'

$ cat Gemfile
source 'https://rubygems.org'
gem 'roar'
gem 'virtus'

$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    axiom-types (0.1.1)
      descendants_tracker (~> 0.0.4)
      ice_nine (~> 0.11.0)
      thread_safe (~> 0.3, >= 0.3.1)
    coercible (1.0.0)
      descendants_tracker (~> 0.0.1)
    descendants_tracker (0.0.4)
      thread_safe (~> 0.3, >= 0.3.1)
    equalizer (0.0.9)
    ice_nine (0.11.1)
    mini_portile (0.6.2)
    multi_json (1.10.1)
    nokogiri (1.6.5)
      mini_portile (~> 0.6.0)
    representable (2.1.3)
      multi_json
      nokogiri
      uber (~> 0.0.7)
    roar (1.0.0)
      representable (>= 2.0.1, <= 3.0.0)
    thread_safe (0.3.4)
    uber (0.0.12)
    virtus (1.0.4)
      axiom-types (~> 0.1)
      coercible (~> 1.0)
      descendants_tracker (~> 0.0, >= 0.0.3)
      equalizer (~> 0.0, >= 0.0.9)

PLATFORMS
  ruby

DEPENDENCIES
  roar
  virtus
```

**Comment by apotonick** [comment]
Yes! :stuck_out_tongue_winking_eye: 

It must be as follows.

```ruby
module SongRep
  include Roar::JSON
  include Roar::Coercion
end
```

**Comment by joevandyk** [comment]
That worked, thanks! Is that by design?

**Comment by apotonick** [comment]
Absolutely, `Coercion` is a feature that works with all engines, e.g. `JSON`, `XML` and `YAML`. Representable does more than just JSON. :wink:
